export interface DiceCategory {
	name: string;
	options: string[];
}

export const diceCategories = {
	animal: [
		"Pigeon",
		"Elephant",
		"Fox",
		"Owl",
		"Penguin",
		"Raccoon",
		"Octopus",
		"Lynx",
		"Hummingbird",
		"Sloth",
		"Chameleon",
		"Red Panda",
		"Giraffe",
		"Seahorse",
		"Koala",
		"Platypus",
		"Meerkat",
		"Flamingo",
		"Narwhal",
		"Capybara",
	],
	color: [
		"Vibrant Blue",
		"Warm Orange",
		"Soft Purple",
		"Electric Green",
		"Deep Crimson",
		"Golden Yellow",
		"Teal",
		"Coral",
		"Indigo",
		"Mint",
		"Burnt Sienna",
		"Rose Gold",
		"Navy",
		"Lavender",
		"Chartreuse",
		"Rust",
		"Sage",
		"Cerulean",
		"Amber",
		"Plum",
	],
	lighting: [
		"Golden Hour",
		"Neon",
		"Soft Studio",
		"Dramatic Spotlight",
		"Moonlight",
		"Candlelight",
		"Harsh Noon",
		"Sunset Glow",
		"Fluorescent",
		"Dappled Forest Light",
		"Cinematic",
		"Blue Hour",
		"Backlit",
		"Rim Lighting",
		"Ambient",
		"High Contrast",
		"Volumetric Rays",
		"Overcast",
		"Fairy Lights",
		"Bioluminescent",
	],
	timeOfDay: [
		"Early Morning",
		"Midday",
		"Late Afternoon",
		"Twilight",
		"Midnight",
		"Dawn",
		"Dusk",
		"Pre-Dawn",
		"Golden Hour",
		"Blue Hour",
		"High Noon",
		"Witching Hour",
		"Sunrise",
		"Sunset",
		"Afternoon",
		"Late Evening",
		"Small Hours",
		"Daybreak",
		"Gloaming",
		"Magic Hour",
	],
	texture: [
		"Smooth Glass",
		"Rough Canvas",
		"Metallic",
		"Velvet",
		"Weathered Wood",
		"Polished Marble",
		"Paper",
		"Fabric",
		"Concrete",
		"Ceramic",
		"Brushed Steel",
		"Cork",
		"Leather",
		"Woven",
		"Granite",
		"Silk",
		"Rubber",
		"Fur",
		"Crystal",
		"Sandstone",
	],
	weather: [
		"Clear Skies",
		"Light Rain",
		"Heavy Storm",
		"Fog",
		"Snow",
		"Partly Cloudy",
		"Overcast",
		"Misty",
		"Sunny",
		"Drizzle",
		"Thunderstorm",
		"Hazy",
		"Sleet",
		"Windy",
		"Humid",
		"Crisp",
		"Breezy",
		"Muggy",
		"Frosty",
		"Scorching",
	],
	style: [
		"Minimalist",
		"Maximalist",
		"Retro 80s",
		"Art Deco",
		"Cyberpunk",
		"Steampunk",
		"Brutalist",
		"Baroque",
		"Mid-Century Modern",
		"Gothic",
		"Victorian",
		"Futuristic",
		"Rustic",
		"Industrial",
		"Scandinavian",
		"Bohemian",
		"Vaporwave",
		"Memphis Design",
		"Bauhaus",
		"Art Nouveau",
	],
	mood: [
		"Energetic",
		"Calm",
		"Mysterious",
		"Playful",
		"Somber",
		"Joyful",
		"Tense",
		"Serene",
		"Dramatic",
		"Whimsical",
		"Melancholic",
		"Optimistic",
		"Eerie",
		"Triumphant",
		"Contemplative",
		"Chaotic",
		"Peaceful",
		"Intense",
		"Nostalgic",
		"Adventurous",
	],
	composition: [
		"Rule of Thirds",
		"Centered",
		"Diagonal",
		"Leading Lines",
		"Frame Within Frame",
		"Symmetrical",
		"Asymmetrical",
		"Low Angle",
		"High Angle",
		"Dutch Angle",
		"Bird's Eye View",
		"Worm's Eye View",
		"Close-up",
		"Wide Shot",
		"Foreground Focus",
		"Background Focus",
		"Layered",
		"Negative Space",
		"Golden Ratio",
		"Radial",
	],
	backgroundDetail: [
		"Bustling City",
		"Empty Desert",
		"Dense Forest",
		"Modern Office",
		"Cozy Cafe",
		"Abstract Shapes",
		"Mountain Range",
		"Ocean Waves",
		"Library Shelves",
		"Art Gallery",
		"Workshop",
		"Garden",
		"Laboratory",
		"Space Station",
		"Bookstore",
		"Street Market",
		"Subway Platform",
		"Rooftop",
		"Underground Cave",
		"Cloud Layer",
	],
	foregroundDetail: [
		"Coffee Cup",
		"Scattered Papers",
		"Potted Plant",
		"Open Laptop",
		"Stack of Books",
		"Pencils and Pens",
		"Eyeglasses",
		"Smartphone",
		"Desk Lamp",
		"Notepad",
		"Mug",
		"Art Supplies",
		"Tools",
		"Food Items",
		"Flowers",
		"Geometric Objects",
		"Vintage Camera",
		"Headphones",
		"Clock",
		"Magnifying Glass",
	],
	perspective: [
		"First Person",
		"Third Person",
		"Over the Shoulder",
		"Profile View",
		"Three-Quarter View",
		"Front Facing",
		"Back View",
		"Isometric",
		"Forced Perspective",
		"Fish-eye",
		"Panoramic",
		"Split Screen",
		"Reflection",
		"Through Window",
		"Mirror View",
		"Shadow Silhouette",
		"Upside Down",
		"Tilted",
		"Extreme Close-up",
		"Distant",
	],
	year: [
		"1920s",
		"1950s",
		"1970s",
		"1980s",
		"1990s",
		"2000s",
		"2020s",
		"2050s",
		"2100s",
		"2200s",
		"Medieval",
		"Renaissance",
		"Victorian Era",
		"Roaring Twenties",
		"Great Depression",
		"Post-War",
		"Swinging Sixties",
		"Disco Era",
		"Digital Age",
		"AI Era",
	],
};

// Simple animal category for single die demo
export const animalDie = diceCategories.animal;

// Categories for Mad Libs style prompt
export const madLibsCategories = [
	{ name: "Animal", key: "animal" as keyof typeof diceCategories },
	{ name: "Color", key: "color" as keyof typeof diceCategories },
	{ name: "Lighting", key: "lighting" as keyof typeof diceCategories },
	{ name: "Time of Day", key: "timeOfDay" as keyof typeof diceCategories },
	{ name: "Texture", key: "texture" as keyof typeof diceCategories },
	{ name: "Mood", key: "mood" as keyof typeof diceCategories },
];

// All categories for full prompt generator
export const allCategories = [
	{ name: "Animal", key: "animal" as keyof typeof diceCategories },
	{ name: "Color Palette", key: "color" as keyof typeof diceCategories },
	{ name: "Lighting", key: "lighting" as keyof typeof diceCategories },
	{ name: "Time of Day", key: "timeOfDay" as keyof typeof diceCategories },
	{ name: "Texture", key: "texture" as keyof typeof diceCategories },
	{ name: "Weather", key: "weather" as keyof typeof diceCategories },
	{ name: "Style", key: "style" as keyof typeof diceCategories },
	{ name: "Mood", key: "mood" as keyof typeof diceCategories },
	{ name: "Composition", key: "composition" as keyof typeof diceCategories },
	{
		name: "Background Detail",
		key: "backgroundDetail" as keyof typeof diceCategories,
	},
	{
		name: "Foreground Detail",
		key: "foregroundDetail" as keyof typeof diceCategories,
	},
	{ name: "Perspective", key: "perspective" as keyof typeof diceCategories },
	{ name: "Time Period", key: "year" as keyof typeof diceCategories },
];

// Helper function to roll a die
export function rollDie(category: keyof typeof diceCategories): string {
	const options = diceCategories[category];
	return options[Math.floor(Math.random() * options.length)];
}

// Helper function to roll multiple dice
export function rollMultipleDice(
	categories: (keyof typeof diceCategories)[],
): Record<string, string> {
	const results: Record<string, string> = {};
	categories.forEach((category) => {
		results[category] = rollDie(category);
	});
	return results;
}

